export const mockChats = [
  {
    id: "1",
    title: "Test El Centro",
    subtitle: "Rodineg, Rodineg, Rodineg JB, Bharat Kumar Ramesh, Periskope",
    last_message: "Hello, Lionita!",
    last_message_time: "08:01",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 43210",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: true,
    messages: [
      {
        id: "101",
        user_id: "2",
        content: "CVFER",
        created_at: "2023-01-22T10:30:00Z",
        type: "text",
        sender: {
          id: "2",
          name: "Rodineg Airtel",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 93456 47523",
        },
      },
      {
        id: "102",
        user_id: "2",
        content: "CDERT",
        created_at: "2023-01-22T11:34:00Z",
        type: "text",
        sender: {
          id: "2",
          name: "Rodineg Airtel",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 93456 47523",
        },
      },
      {
        id: "103",
        user_id: "2",
        content: "Hello, South Euna!",
        created_at: "2023-01-22T12:01:00Z",
        type: "text",
        sender: {
          id: "2",
          name: "Rodineg Airtel",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 93456 47523",
        },
      },
      {
        id: "104",
        user_id: "2",
        content: "Hello, Lionita!",
        created_at: "2023-01-23T08:01:00Z",
        type: "text",
        sender: {
          id: "2",
          name: "Rodineg Airtel",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 93456 47523",
        },
      },
      {
        id: "105",
        user_id: "2",
        content: "CDERT",
        created_at: "2023-01-23T09:43:00Z",
        type: "text",
        sender: {
          id: "2",
          name: "Rodineg Airtel",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 93456 47523",
        },
      },
    ],
  },
  {
    id: "2",
    title: "Test Skope Final 5",
    subtitle: "Support2: This doesn't go on Tuesday",
    last_message: "This doesn't go on Tuesday",
    last_message_time: "Yesterday",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009 35",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "3",
    title: "Periskope Team Chat",
    subtitle: "Periskope: Test message",
    last_message: "Test message",
    last_message_time: "28-Feb-23",
    unread_count: 1,
    labels: ["Demo", "Internal"],
    phone_number: "+91 98765 44009 35",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: true,
    messages: [
      {
        id: "301",
        user_id: "3",
        content: "hello",
        created_at: "2023-02-28T14:30:00Z",
        type: "text",
        sender: {
          id: "3",
          name: "Periskope",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 98765 44009",
        },
      },
    ],
  },
  {
    id: "4",
    title: "+91 99999 99999",
    subtitle: "Hi there, I'm Swapnika, Co-Founder of Periskope",
    last_message: "Hi there, I'm Swapnika, Co-Founder of Periskope",
    last_message_time: "22-Feb-23",
    unread_count: 0,
    labels: ["Demo", "Signup"],
    phone_number: "+91 98765 44009 31",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "5",
    title: "Test Demo17",
    subtitle: "Rohusan: 123",
    last_message: "123",
    last_message_time: "25-Feb-23",
    unread_count: 0,
    labels: ["Content", "Demo"],
    phone_number: "+91 98765 44009 51",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "6",
    title: "Test El Centro",
    subtitle: "Rodineg: Hello, Ahmedport!",
    last_message: "Hello, Ahmedport!",
    last_message_time: "24-Feb-23",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "7",
    title: "Testing group",
    subtitle: "✓ Testing 12345",
    last_message: "Testing 12345",
    last_message_time: "21-Jan-23",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: true,
    messages: [
      {
        id: "701",
        user_id: "3",
        content: "test el centro",
        created_at: "2023-01-21T09:30:00Z",
        type: "text",
        sender: {
          id: "3",
          name: "Periskope",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 98765 44009",
        },
      },
      {
        id: "702",
        user_id: "3",
        content: "testing",
        created_at: "2023-01-21T09:35:00Z",
        type: "text",
        sender: {
          id: "3",
          name: "Periskope",
          avatar: "/placeholder.svg?height=40&width=40",
          phone: "+91 98765 44009",
        },
      },
    ],
  },
  {
    id: "8",
    title: "Yasin 3",
    subtitle: "✓ First Bulk Message",
    last_message: "First Bulk Message",
    last_message_time: "20-Dec-22",
    unread_count: 0,
    labels: ["Demo", "Dont Send"],
    phone_number: "+91 98765 44009 34",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "9",
    title: "Test Skope Final 9473",
    subtitle: "✓ Heyy",
    last_message: "Heyy",
    last_message_time: "01-Jan-23",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009 39",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "10",
    title: "Skope Demo",
    subtitle: "✓ test 123",
    last_message: "test 123",
    last_message_time: "20-Dec-22",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
  {
    id: "11",
    title: "Test Demo15",
    subtitle: "✓ test 123",
    last_message: "test 123",
    last_message_time: "20-Dec-22",
    unread_count: 0,
    labels: ["Demo"],
    phone_number: "+91 98765 44009",
    avatar: "/placeholder.svg?height=40&width=40",
    is_group: false,
    messages: [],
  },
]

